name: Unzip Media
on: push
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract Files
        run: |
          unzip -o zooniverse.zip
          rm zooniverse.zip
      - name: Commit Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Extracted media files" || exit 0
          git push
